# use the shared Yast defaults
inherit_from:
  - .rubocop_todo.yml
  - /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Include:
    - "library/*/src/lib/**/*.rb"
