# use the shared Yast defaults
inherit_from:
  - /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml
  - .rubocop_todo.yml

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Include:
    - "library/*/src/lib/**/*.rb"

# TODO: enable it, just ENOTIME
# Offense count: 21
Lint/Loop:
  Exclude:
    - 'src/clients/files_auto.rb'
    - 'src/clients/inst_autosetup.rb'
    - 'src/clients/inst_autosetup_upgrade.rb'
    - 'src/clients/report_auto.rb'
    - 'src/clients/software_auto.rb'
    - 'src/include/autoinstall/classes.rb'
    - 'src/include/autoinstall/dialogs.rb'
    - 'src/include/autoinstall/general_dialogs.rb'
    - 'src/include/autoinstall/script_dialogs.rb'
    - 'src/modules/Profile.rb'
    - 'src/modules/ProfileLocation.rb'

# TODO: enable it, just ENOTIME
# Offense count: 7
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'src/clients/inst_autoinit.rb'
    - 'src/include/autoinstall/conftree.rb'
    - 'src/include/autoinstall/general_dialogs.rb'

# TODO: enable it, just ENOTIME
# Offense count: 27
# Configuration parameters: AllowKeywordBlockArguments.
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'src/clients/inst_autoconfigure.rb'
    - 'src/clients/inst_autopost.rb'
    - 'src/include/autoinstall/classes.rb'
    - 'src/include/autoinstall/conftree.rb'
    - 'src/modules/AutoInstallRules.rb'
    - 'src/modules/Profile.rb'
    - 'src/modules/Y2ModuleConfig.rb'

# Offense count: 95
Metrics/AbcSize:
  Max: 448

# Offense count: 105
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 500

# Offense count: 64
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 7

# Offense count: 15
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1000

# Offense count: 82
Metrics/CyclomaticComplexity:
  Max: 78

# Offense count: 112
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 526

# Offense count: 12
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1062

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 10

# Offense count: 81
Metrics/PerceivedComplexity:
  Max: 87

# TODO: enable it, just ENOTIME
# Offense count: 1
# Configuration parameters: EnforcedStyleForLeadingUnderscores.
# SupportedStylesForLeadingUnderscores: disallowed, required, optional
Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'src/modules/AutoinstFunctions.rb'

# Offense count: 361
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Enabled: false

# TODO: enable it, just ENOTIME
# Offense count: 16
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
Naming/UncommunicativeBlockParamName:
  Exclude:
    - 'src/clients/clone_system.rb'
    - 'src/include/autoinstall/PartitionDialog.rb'
    - 'src/include/autoinstall/dialogs.rb'
    - 'src/modules/AutoinstClone.rb'
    - 'src/modules/AutoinstPartPlan.rb'
    - 'src/modules/AutoinstSoftware.rb'
    - 'src/modules/Profile.rb'

# TODO: enable it, just ENOTIME
# Offense count: 91
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db
Naming/UncommunicativeMethodParamName:
  Enabled: false

# Offense count: 573
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Enabled: false

# TODO: enable it, just ENOTIME
# Offense count: 81
Style/Documentation:
  Enabled: false

# TODO: enable it, just ENOTIME
# Offense count: 29
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# TODO: enable it, just ENOTIME
# Offense count: 31
Style/MultipleComparison:
  Exclude:
    - 'src/clients/files_auto.rb'
    - 'src/clients/report_auto.rb'
    - 'src/include/autoinstall/PartitionDialog.rb'
    - 'src/include/autoinstall/StorageDialog.rb'
    - 'src/include/autoinstall/ask.rb'
    - 'src/include/autoinstall/classes.rb'
    - 'src/include/autoinstall/conftree.rb'
    - 'src/include/autoinstall/dialogs.rb'
    - 'src/include/autoinstall/general_dialogs.rb'
    - 'src/include/autoinstall/script_dialogs.rb'
    - 'src/modules/AutoInstallRules.rb'
    - 'src/modules/AutoinstConfig.rb'
    - 'src/modules/AutoinstScripts.rb'
