

CATALOG="./catalog.xml"
XSLTPROC="/usr/bin/xsltproc"

chunks:
	XML_CATALOG_FILES=$(CATALOG) \
	xsltproc \
	-stringparam base.dir "build/" \
	--xinclude \
	chunks.xsl \
	autoyast.xml


autoyast.fo: print.xsl
	XML_CATALOG_FILES=$(CATALOG) \
	$(XSLTPROC) --output autoyast.fo --xinclude  print.xsl  autoyast.xml


pdf: autoyast.fo
	fop autoyast.fo autoyast.pdf
