#! /bin/sh
# Copyright (c) 1995-2004 SUSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# Author: Anas Nashif
# Please send feedback to http://www.suse.de/feedback/
#
# /etc/init.d/autoyast
#
# LSB compatible service control script; see http://www.linuxbase.org/spec/
# 
#
### BEGIN INIT INFO
# Provides:          autoyast
# Required-Start:    $syslog $remote_fs $network
# Should-Start: $time ypbind sendmail hwscan
# Required-Stop:
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: A start script to execute autoyast scripts
# Description:       Execute autoyast scripts 
### END INIT INFO


LOG_DIR="/var/adm/autoinstall/logs"
SCRIPT_DIR="/var/adm/autoinstall/scripts"
INITSCRIPT_DIR="/var/adm/autoinstall/init.d"

if [ ! -d "$INITSCRIPT_DIR" ]; then
    exit 1
fi

for script in  `find $INITSCRIPT_DIR -type f`; do
    CONTINUE=1
done

if [ -z "$CONTINUE" ]; then
    exit 0
fi

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     be verbose in local rc status and clear it afterwards
#      rc_status -v -r  ditto and clear both the local and overall rc status
#      rc_status -s     display "skipped" and exit with status 3
#      rc_status -u     display "unused" and exit with status 3
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num>
#      rc_reset         clear both the local and overall rc status
#      rc_exit          exit appropriate to overall rc status
#      rc_active        checks whether a service is activated by symlinks
#      rc_splash arg    sets the boot splash screen to arg (if active)
. /etc/rc.status

# Reset status of this service
rc_reset

# Return values acc. to LSB for all commands but status:
# 0	  - success
# 1       - generic or unspecified error
# 2       - invalid or excess argument(s)
# 3       - unimplemented feature (e.g. "reload")
# 4       - user had insufficient privileges
# 5       - program is not installed
# 6       - program is not configured
# 7       - program is not running
# 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)
# 
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signaling is not supported) are
# considered a success.


case "$1" in
    start)
	# Remember status and be verbose
        for script in  `find $INITSCRIPT_DIR -type f`; do
            echo -n "Executing AutoYaST script: $script"
            BASENAME=`basename $script`
            sh -x $script  2&> $LOG_DIR/$BASENAME.log
            mv $script $SCRIPT_DIR
	    rc_status -v
        done
        chkconfig autoyast off
	;;
    stop)
        # Do nothing
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac
rc_exit
